# Generated by Django 4.1.5 on 2023-02-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
