# Generated by Django 4.1.5 on 2023-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='Employee_Otp',
            field=models.CharField(max_length=100),
        ),
    ]
