# Generated by Django 4.1.5 on 2023-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0004_alter_otp_employee_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='Otp',
            field=models.CharField(default=123123, max_length=10),
            preserve_default=False,
        ),
    ]
