# Generated by Django 4.1.5 on 2023-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0005_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='Otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='Secret_key',
            field=models.CharField(default=8787879779877897, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='Employee_Otp',
            field=models.IntegerField(),
        ),
    ]
