# Generated by Django 4.1.5 on 2023-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0006_remove_otp_otp_otp_secret_key_alter_otp_employee_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='Secret_key',
        ),
        migrations.AddField(
            model_name='otp',
            name='Otp',
            field=models.CharField(default=5456465454, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='Employee_Otp',
            field=models.CharField(max_length=100),
        ),
    ]
