# Generated by Django 4.1.5 on 2023-02-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_feedback', '0007_remove_otp_secret_key_otp_otp_alter_otp_employee_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='Employee_Otp',
            new_name='Employee_Secret_key',
        ),
    ]
